### PR TITLE
Use rust-id3 in favour of TagLib

### PR DESCRIPTION
**Pull request by lewisbelcher**
As the title says. This removes the requirement to install an external dependency and should increase stability ([`taglib`](https://github.com/ebassi/taglib-rust/) contains quite a lot of unsafe code and throws a seg fault on some OSes (Alpine Linux for example)).

Things to note:
- The interface for `taglib` was just lifted straight out of that crate. Various functions which are exposed by `taglib` are not implemented here, however. I've only implemented what is needed.
- The README has been updated with appropriate changes (I also took the liberty for make a couple of other minor improvements).

### CODE REVIEW

**Comment by lewisbelcher** [comment]
Ready for review @cdown :)

**Comment by cdown** [comment]
Thanks! A question: why not change the existing code to fit the new id3 library calls, rather than shimming it as taglib? Since it's just going to get deprecated, it seems fine to (for example) remove .save() calls.

**Comment by lewisbelcher** [comment]
No problem :)

The only reason for the shim was to be as unintrusive as possible on the existing code. If you're happy with committing to id3 then I'll implement some more far-reaching changes.

**Comment by cdown** [comment]
Just to poke this, this is still a more than welcome change :-) I think the only thing to adjust was to avoid having a taglib-esque wrapper.

**Comment by cdown** [comment]
Thanks for your work on this! ce92a8a6363d644ad29afe361f5438956a212fc7 now uses rust-id3 directly and will be in the next release.

**Pull request closed without merging**
